### PR TITLE
Update Dev and Alpha Watermark

### PR DESCRIPTION
**Pull request by nevespt**

### CODE REVIEW

**Comment by RileyTheFox** [comment]
I'm not sure I understand the change here. Why does this need changing?

**Comment by nevespt** [comment]
bcz it wasnt showing before also Pre-release is diferent then dev builds

**Comment by RileyTheFox** [comment]
We don't really differentiate what the build type is. It's either a stable release or not (prerelease, dev, whatever you want to call it)

**Comment by nevespt** [comment]
so keep just the Pre-Release text whatever the version is 1.23.1b or .1.23.1-a12?

**Comment by RileyTheFox** [comment]
Yeah the text doesn't really need changing. The version itself more or less denotes what the build type is.

**Pull request closed without merging**
