### PR TITLE
Note model fixes

### PR DESCRIPTION
**Pull request by Purplo-cf**
Fixed display of 4-lane and 5-lane drum notes for ghosts and accents on pads and cymbals:
Finished_note_models

### CODE REVIEW

**Comment by kaduwaengertner** [comment]
I would wait on approving this, the screenshots dont match the proposed designs discussed with the team and we did some changes today on stream, we doing a call this weekend to check all note designs and get final approval.

**Comment by Purplo-cf** [comment]
Just following up on this - do you have final approved designs that I can take a look at? Has anybody started implementing them already?

**Comment by EliteAsian123** [comment]
Not that I know of, no

**Comment by EliteAsian123** [comment]
Although, I am willing to merge this in the mean time while the actual models are getting ready as this is a huge improvement to the ones in-game at the moment. If you fix the merge conflict I'll merge it!

**Comment by Purplo-cf** [comment]
Okay, I rebased on the latest `engine-refactor` version this morning and the Unity files stayed intact. This should be ready to merge

**Pull request merged**
